version: "3.9"
services:
  robonet:
    image: robonet-base
    container_name: robonet_$USER
    build:
      context: widowx_envs
    entrypoint: ./widowx_envs/scripts/run.sh
    environment:
      - DISPLAY=:0
    user: robonet:1002
    stdin_open: true
    tty: true
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    runtime: nvidia
    volumes:
      - ${USB_CONNECTOR_CHART:-/dev/null}:/tmp/camera_connector_chart
      # if you want to be able to edit widowx_envs code without rebuilding the image, this
      # overwrites the widowx_envs directory that was copied in at build time
      - ./experiments:/home/robonet/experiments
      - /mount/harddrive/:/home/robonet/trainingdata  # TODO (YL): better way to mount a local directory
      # $HOME/widowx_data:/home/robonet/trainingdata
      - ./widowx_envs:/home/robonet/widowx_envs
      - /dev:/dev  # for host tty access

  bridge_data_v2:
    image: robonet-bridge-data-v2
    container_name: robonet_${USER}_bridge_data_v2
    user: robonet:1002
    build:
      context: code/bridge_data_v2
    network_mode: host
    environment:
      - WANDB_API_KEY=putwandbkeyhere
    runtime: nvidia
    volumes:
      - ./widowx_envs:/home/robonet/widowx_envs 
      - ./code/bridge_data_v2:/home/robonet/code/bridge_data_v2
      - ./experiments:/home/robonet/experiments
      - /mount/harddrive/:/home/robonet/trainingdata

  jaxrl_minimal:
    image: robonet-jaxrl-min
    container_name: robonet_${USER}_jaxrl_min
    user: robonet:1002
    build:
      context: code/jaxrl_minimal
    network_mode: host
    environment:
      - WANDB_API_KEY=putwandbkeyhere
    runtime: nvidia
    volumes:
      - ./widowx_envs:/home/robonet/widowx_envs 
      - ./code/jaxrl_minimal:/home/robonet/code/jaxrl_minimal
      - ./code/denoising-diffusion-flax:/home/robonet/code/denoising-diffusion-flax
      - ./experiments:/home/robonet/experiments
      - /mount/harddrive/:/home/robonet/trainingdata

  orca:
    image: robonet-orca
    container_name: robonet_${USER}_orca
    user: robonet:1002
    build:
      context: code/orca
    network_mode: host
    environment:
      - WANDB_API_KEY=022ddeef4fdea91a8015522e21b5821ee6e123cb
    runtime: nvidia
    volumes:
      - ./widowx_envs:/home/robonet/widowx_envs 
      - ./code/orca:/home/robonet/code/orca
      - ./experiments:/home/robonet/experiments
      - /mount/harddrive/:/home/robonet/trainingdata
